### ISSUE TITLE
ModuleNotFoundError : No module named 'caviar.prody_parser.kdtree._CKDTree'

### ISSUE THREAD

**Issue by leelasd** [jr-marchand/caviar#3]
Hi, 

Thanks for writing this package. I have read your paper and I am very impressed by the results you have shown. 
I have tried to install `Caviar` on my Mac to do some testing. I have come across  the following bug. Any suggestions on how to resolve this is would be highly appreciated. 

I am using python 3.7.8 and the OS is macos catalina verson 10.15.6

```
Traceback (most recent call last):
  File "/Users/leeladodda/anaconda3/envs/caviar/bin/caviar", line 33, in <module>
    sys.exit(load_entry_point('caviar==1.1.0', 'console_scripts', 'caviar')())
  File "/Users/leeladodda/anaconda3/envs/caviar/lib/python3.7/site-packages/pkg_resources/__init__.py", line 488, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/leeladodda/anaconda3/envs/caviar/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2872, in load_entry_point
    return ep.load()
  File "/Users/leeladodda/anaconda3/envs/caviar/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2472, in load
    return self.resolve()
  File "/Users/leeladodda/anaconda3/envs/caviar/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2478, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/leeladodda/anaconda3/envs/caviar/lib/python3.7/site-packages/caviar/caviar.py", line 7, in <module>
    from caviar.prody_parser import *
  File "/Users/leeladodda/anaconda3/envs/caviar/lib/python3.7/site-packages/caviar/prody_parser/__init__.py", line 73, in <module>
    from . import kdtree
  File "/Users/leeladodda/anaconda3/envs/caviar/lib/python3.7/site-packages/caviar/prody_parser/kdtree/__init__.py", line 5, in <module>
    from .kdtree import KDTree
  File "/Users/leeladodda/anaconda3/envs/caviar/lib/python3.7/site-packages/caviar/prody_parser/kdtree/kdtree.py", line 18, in <module>
    from ._CKDTree import KDTree as _KDTree
ModuleNotFoundError: No module named 'caviar.prody_parser.kdtree._CKDTree'
```

Thanks for making the code available and great work.

Best wishes,
Leela

**Comment by jr-marchand** [comment]
Hi Leela,
thanks a lot for the nice comments and for the interest!

I literally pushed a new version *yesterday*, few hours before your message! And since the new code requires two external libraries in C and C++, I should have adjusted the conda package.

### Option 1: I created an osx conda package. Maybe it works, but I don't have a Mac to test it.
Could you please try to:
 - remove this broken environment: ```conda env remove -n caviar```
 - try again to install caviar (it should automatically detect the osx package and take this one by default): ```conda create -n caviar -c jr-marchand caviar``` and activate it ```conda activate caviar```
 - And try again: ```caviar -code 4qsr```

### Option 2: Use the previous CAVIAR version (1.0.1)
In case Option 1 still does not work, you should be able to use the previous version for now (without CIF/DCD support), which you can install with: ```conda create -n caviar_old -c jr-marchand caviar=1.0```.

### Alternative option: build the package yourself with setup.py
In that case, you would need to have the dependencies installed and the easiest way imo is the following.
- Clone the repository: ```git clone https://github.com/jr-marchand/caviar.git```
- Create a (broken, but with the required dependencies) CAVIAR environment: ```conda create -n caviar -c jr-marchand caviar``` and activate it ```conda activate caviar```
- Remove the broken CAVIAR package without removing the dependencies: ```conda remove caviar --force-remove```
- Go to the source code folder, and execute ```python setup.py install```
That should install CAVIAR, including compiling the two files in C and C++. And both ```caviar``` and ```caviar_gui``` should be accessible.


Hopefully the first solution works. Please let me know!
Cheers,
JR

**Comment by leelasd** [comment]
Thank you so much @jr-marchand, Alternative strategy worked for me (doing `python setup.py install` ) Here is a visual by opening caviar files in ChimeraX

<img width="1216" alt="testing_caviar" src="https://user-images.githubusercontent.com/7967695/90890780-a31f0d00-e388-11ea-9d40-3969369ae96a.png">

**Comment by jr-marchand** [comment]
Thanks a lot for the feedback! I'm glad to see it works.
I'll try again to generate a working conda package once I get access to an Apple computer.
